services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"  # host:container

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"  # host:container
